const emojiList = {
  "😄": "Grinning Face With Smiling Eyes",
  "😂": "Face With Tears of Joy",
  "😉": "Winking Face",
  "😊": "Smiling Face With Smiling Eyes",
  "😇": "Smiling Face With Halo",
  "🙂": "Slightly Smiling Face",
  "😌": "Relieved Face",
  "😍": "Smiling Face With Heart-Eyes",
  "🥰": "Smiling face with smiling eyes and three hearts",
  "😘": "Face Blowing a Kiss",
  "🤩": "Smirking Face With Starry Eyes",
  "😙": "Kissing Face With Smiling Eyes",
  "😚": "Kissing Face With Closed Eyes",
  "😗": "Kissing Face",
  "😋": "Face Savouring Delicious Food",
  "😛": "Face With Stuck-Out Tongue",
  "😝": "Face With Stuck-Out Tongue & Tightly Closed Eyes",
  "😜": "Face With Stuck-Out Tongue & Winking Eye",
  "🤓": "Nerd Face",
  "🤪": "Crazy Face",
  "🤨": "Face With a Raised Eyebrow",
  "🧐": "Face With Monocle",
  "😃": "Smiling Face With Open Mouth",
  "😎": "Face With Sunglasses",
  "😱": "Face Screaming in Fear",
  "😀": "Grinning Face",
  "😁": "Beaming Face with Smiling Eyes",
  "😆": "Grinning Squinting Face",
  "😅": "Grinning Face with Sweat",
  "🤣": "Rolling on the Floor Laughing",
  "🙃": "Upside-Down Face",
  "🤑": "Money-Mouth Face",
  "🤗": "Hugging Face",
  "🤭": "Face with Hand Over Mouth",
  "🤫": "Shushing Face",
  "🤔": "Thinking Face",
  "🤐": "Zipper-Mouth Face",
  "😐": "Neutral Face",
  "😑": "Expressionless Face",
  "😶": "Face Without Mouth",
  "😏": "Smirking Face",
  "😒": "Unamused Face",
  "🙄": "Face with Rolling Eyes",
  "😬": "Grimacing Face",
  "🤥": "Lying Face",
  "😔": "Pensive Face",
  "😪": "Sleepy Face",
  "🤤": "Drooling Face",
  "😴": "Sleeping Face",
  "😷": "Face with Medical Mask",
  "🤒": "Face with Thermometer",
  "🤕": "Face with Head-Bandage",
  "😕": "Confused Face",
  "😟": "Worried Face",
  "🙁": "Slightly Frowning Face",
  "😮": "Face with Open Mouth",
  "😯": "Hushed Face",
  "😲": "Astonished Face",
  "😳": "Flushed Face",
  "🥺": "Pleading Face",
  "😦": "Frowning Face with Open Mouth",
  "😧": "Anguished Face",
  "😨": "Fearful Face",
  "😰": "Anxious Face with Sweat",
  "😥": "Sad but Relieved Face",
  "😢": "Crying Face",
  "😭": "Loudly Crying Face",
  "😖": "Confounded Face",
  "😣": "Persevering Face",
  "😞": "Disappointed Face",
  "😓": "Downcast Face with Sweat",
  "😩": "Weary Face",
  "😫": "Tired Face",
  "🥱": "Yawning Face",
  "😤": "Face with Steam From Nose"
};

export default emojiList;
