const emojiList = {
  "😀": "Grinning Face",
  "😃": "Smiling Face With Open Mouth",
  "😄": "Smiling Face With Open Mouth And Smiling Eyes",
  "😁": "Grinning Face With Smiling Eyes",
  "😆": "Smiling Face With Open Mouth And Closed Eyes",
  "😅": "Smiling Face With Open Mouth & Cold Sweat",
  "😂": "Face With Tears of Joy",
  "🤣": "Rolling On The Floor, Laughing",
  "😳": "Flushed Face",
  "😊": "Smiling Face With Smiling Eyes",
  "😇": "Smiling Face With Halo",
  "🙂": "Slightly Smiling Face",
  "🙃": "Upside-Down Face",
  "😉": "Winking Face",
  "😌": "Relieved Face",
  "😍": "Smiling Face With Heart-Eyes",
  "🥰": "Smiling face with smiling eyes and three hearts",
  "😘": "Face Throwing a Kiss",
  "😗": "Kissing Face",
  "😙": "Kissing Face With Smiling Eyes",
  "😚": "Kissing Face With Closed Eyes",
  "😋": "Face Savouring Delicious Food",
  "😛": "Face With Stuck-Out Tongue",
  "😝": "Face With Stuck-Out Tongue & Tightly Closed Eyes",
  "😜": "Face With Stuck-Out Tongue & Winking Eye",
  "🤪": "Crazy Face",
  "🤨": "Face With a Raised Eyebrow",
  "🧐": "Face With Monocle",
  "🤓": "Nerd Face",
  "😎": "Face With Sunglasses",
  "🤩": "Smirking Face With Starry Eyes",
  "🥳": "Face with party blower and party hat"
};

export default emojiList;
