const emojiList = {
  "🙈": "See-No-Evil Monkey",
  "😄": "Smiling Face With Open Mouth And Smiling Eyes",
  "😁": "Grinning Face With Smiling Eyes",
  "😆": "Smiling Face With Open Mouth And Closed Eyes",
  "🔥": "Hot",
  "😂": "Face With Tears of Joy",
  "😉": "Winking Face",
  "🙎‍♀️": "Woman Pouting",
  "👋": "Waving Hand",
  "😊": "Smiling Face With Smiling Eyes",
  "😇": "Smiling Face With Halo",
  "🙂": "Slightly Smiling Face",
  "🙏": "Folded Hands",
  "😌": "Relieved Face",
  "😍": "Smiling Face With Heart-Eyes",
  "🥰": "Smiling face with smiling eyes and three hearts",
  "😘": "Face Throwing a Kiss",
  "🤩": "Smirking Face With Starry Eyes",
  "😙": "Kissing Face With Smiling Eyes",
  "😚": "Kissing Face With Closed Eyes",
  "😗": "Kissing Face",
  "😋": "Face Savouring Delicious Food",
  "😛": "Face With Stuck-Out Tongue",
  "😝": "Face With Stuck-Out Tongue & Tightly Closed Eyes",
  "😜": "Face With Stuck-Out Tongue & Winking Eye",
  "🤓": "Nerd Face",
  "🤪": "Crazy Face",
  "🤨": "Face With a Raised Eyebrow",
  "🧐": "Face With Monocle",
  "😃": "Smiling Face With Open Mouth",
  "😎": "Face With Sunglasses",
  "💪": "Flexed Biceps",
  "👹": "Ogre",
  "😱": " Face Screaming in Fear"
};

export default emojiList;
